{"https://www.metacritic.com/browse/movie/?releaseYearMin=1910&releaseYearMax=2024&page=": {"count": 37, "list index out of range": 10, "HTTPSConnectionPool(host='www.metacritic.com', port=443): Max retries exceeded with url: /browse/movie/?releaseYearMin=1910&releaseYearMax=2024&page=50 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000013DFC637F10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='www.metacritic.com', port=443): Max retries exceeded with url: /browse/movie/?releaseYearMin=1910&releaseYearMax=2024&page=52 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000013DFC615AF0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='www.metacritic.com', port=443): Max retries exceeded with url: /browse/movie/?releaseYearMin=1910&releaseYearMax=2024&page=58 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000025EF410B880>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "Can't fetch current ip, even after retrying... Check your internet connection.": 10, "HTTPSConnectionPool(host='www.metacritic.com', port=443): Max retries exceeded with url: /browse/movie/?releaseYearMin=1910&releaseYearMax=2024&page=475 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002086D30C190>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='www.metacritic.com', port=443): Max retries exceeded with url: /browse/movie/?releaseYearMin=1910&releaseYearMax=2024&page=480 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002086D0AA6D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='www.metacritic.com', port=443): Max retries exceeded with url: /browse/movie/?releaseYearMin=1910&releaseYearMax=2024&page=481 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002086D0AA580>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))": 1, "('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))": 2, "HTTPSConnectionPool(host='www.metacritic.com', port=443): Max retries exceeded with url: /browse/movie/?releaseYearMin=1910&releaseYearMax=2024&page=637 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002086DFA90A0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='www.metacritic.com', port=443): Max retries exceeded with url: /browse/movie/?releaseYearMin=1910&releaseYearMax=2024&page=638 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002086D112160>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='www.metacritic.com', port=443): Max retries exceeded with url: /browse/movie/?releaseYearMin=1910&releaseYearMax=2024&page=640 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002086DA204C0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='www.metacritic.com', port=443): Max retries exceeded with url: /browse/movie/?releaseYearMin=1910&releaseYearMax=2024&page=650 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002086E7FAE80>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='www.metacritic.com', port=443): Max retries exceeded with url: /browse/movie/?releaseYearMin=1910&releaseYearMax=2024&page=652 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002086DB79D00>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='www.metacritic.com', port=443): Max retries exceeded with url: /browse/movie/?releaseYearMin=1910&releaseYearMax=2024&page=653 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002086BF00700>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='www.metacritic.com', port=443): Max retries exceeded with url: /browse/movie/?releaseYearMin=1910&releaseYearMax=2024&page=654 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002086BF00FA0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "[Errno 13] Permission denied: 'C:\\\\Users\\\\Burt\\\\Documents\\\\Git\\\\podcast\\\\movies.xlsx'": 1}, "https://www.imdb.com/find/?q=": {"count": 342, "name 'parse_json' is not defined": 1, "[Errno 13] Permission denied: 'C:\\\\Users\\\\Burt\\\\Documents\\\\Git\\\\podcast\\\\movies.xlsx'": 3, "'NoneType' object has no attribute 'text'": 85, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt0090056/?ref_=fn_al_tt_1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020DBEF75B20>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=hero&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000278378B4B80>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=the%20saint&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027837EC1D90>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))": 34, "Can't fetch current ip, even after retrying... Check your internet connection.": 15, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=stronger&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027839D14070>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt2543472/?ref_=fn_al_tt_1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002783755F970>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "(\"Connection broken: ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)\", ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))": 27, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt0167404/?ref_=fn_al_tt_1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020652980310>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=knives%20out&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000206529803D0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))": 26, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt0097737/?ref_=fn_al_tt_1 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=citizen%20kane&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000206528A4A60>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=fargo&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020652880550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=harry%20potter%20and%20the%20deathly%20hallows:%20part%202&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020652880DC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=lock,%20stock%20and%20two%20smoking%20barrels&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020652880DF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt0094625/?ref_=fn_al_tt_1 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))": 1, "(\"Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)\", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))": 5, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt0112864/?ref_=fn_al_tt_1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000206523275B0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /title/tt1542344/?ref_=fn_al_tt_1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020652290E80>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt1790885/?ref_=fn_al_tt_1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020652D04100>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=spider-man:%20far%20from%20home&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020654390100>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=mission:%20impossible%20-%20rogue%20nation&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020654390490>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt0120917/?ref_=fn_al_tt_1 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=high%20fidelity&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020653EF9AC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=up%20in%20the%20air&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020653EF9E80>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=a%20bridge%20too%20far&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020653EF99D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=the%20terminal&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020653EF99D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=downton%20abbey&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002065491EC70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=mary%20and%20max&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000023565098B20>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt0110367/?ref_=fn_al_tt_2 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt1289403/?ref_=fn_al_tt_1 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=the%20basketball%20diaries&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000023563DA38B0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt0335345/?ref_=fn_al_tt_1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000023564F9B490>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=willow&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000023564F981F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=from%20dusk%20till%20dawn&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000023564F982B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=king%20kong&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000023564F98340>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=tommy%20boy&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000235652CA220>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt17676734/?ref_=fn_al_tt_1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002356528F850>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=definitely,%20maybe&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002356563D370>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt7798634/?ref_=fn_al_tt_1 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=legend&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000235638F0E80>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "[WinError 10054] An existing connection was forcibly closed by the remote host": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt1190080/?ref_=fn_al_tt_1 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=21%20bridges&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E80102CD60>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt1524515/?ref_=fn_al_tt_1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E801965C70>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=6%20souls&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E8030D6D60>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=6%20underground&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E8019653A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=65&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E8018106D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=9%C2%BD%20weeks&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E8018108E0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt0118583/?ref_=fn_al_tt_1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E8034F5610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt2406566/?ref_=fn_al_tt_1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E801677880>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=austin%20powers%20in%20goldmember&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E801669610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=austin%20powers:%20the%20spy%20who%20shagged%20me&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E8016696A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt8337264/?ref_=fn_al_tt_1 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt21301418/?ref_=fn_al_tt_1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E8013B67F0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt1528854/?ref_=fn_al_tt_1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E8033D01C0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=damage&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E87FE70790>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=damaged&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E87FE70040>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt4123432/?ref_=fn_al_tt_1 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=fantastic%20four&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E80364E8B0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=fantasy%20island&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E803622940>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=far%20haven&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E803622A00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=farrey&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E803622B80>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt1798632/?ref_=fn_al_tt_2 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=first%20daughter&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E80113EC70>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=mother!&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E87FE62760>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=mothers'%20instinct&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E87FE62700>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt14998742/?ref_=fn_al_tt_1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E802ED9610>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=rebel%20moon%20-%20part%20two:%20the%20scargiver&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E80126F070>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=red%20eye&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E8015CEF10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=red%20notice&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E80331F760>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=dekalog%20(1988)&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000015733FEA370>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='m.imdb.com', port=443): Max retries exceeded with url: /title/tt4935462/?ref_=fn_al_tt_2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001573600E8B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=the%20right%20stuff&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000015734BD0B20>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=the%20sweet%20hereafter&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000015734BD3790>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=the%20passenger%20(re-release)&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000015734C21730>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt5375040/?ref_=fn_al_tt_1 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt0108065/?ref_=fn_al_tt_1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000015734B2CA30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=still%20walking&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000015734B2CAF0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=last%20train%20home&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000015736333DC0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=let%20the%20fire%20burn&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000015736323820>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=like%20water%20for%20chocolate&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000015736309670>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=little%20men&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000157363098B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=los%20angeles%20plays%20itself&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000015736309910>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=the%20big%20sleep&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000157349F88B0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=the%20double%20life%20of%20veronique&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000157349F88B0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=the%20gleaners%20&%20i&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000157349FB5B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=the%20great%20beauty&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000157349FB100>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt0099703/?ref_=fn_al_tt_1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000015733C4C910>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=the%20inheritance&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000015733C4C9D0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=the%20interrupters&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000157349F6C70>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=about%20schmidt&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001573628F520>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt12810814/?ref_=fn_al_tt_2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001573416E5E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=forbidden%20lie$&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001573416E1F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=from%20here%20to%20eternity&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000157334F0F70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt2334649/?ref_=fn_al_tt_1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000015733E98700>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=meek's%20cutoff&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000015734904760>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=mona%20lisa&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001573491B4C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "cannot set a row with mismatched columns": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=so%20long,%20my%20son&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019D9226B550>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=about%20dry%20grasses&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019D91CB72B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=amour&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019D91CB7DF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=paris,%20texas&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019D91CB7DF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=young%20frankenstein&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019D9226B5B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=4%20months,%203%20weeks,%202%20days&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019D91313160>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=snack%20shack&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019D910DF280>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=causeway&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019D910DFBB0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=lowlifes&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019D93C54700>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt23186596/?ref_=fn_al_tt_2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019D93C58100>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt14824590/?ref_=fn_al_tt_1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019D91AAA4C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt0252866/?ref_=fn_al_tt_1 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /find/?q=dirty%20grandpa&ref_=nv_sr_sm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019D9219A310>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt9013340/?ref_=fn_al_tt_1 (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))": 1, "name 'headers' is not defined": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt0056592/ (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt0206634/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A36A7566A0>: Failed to establish a new connection: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions'))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt0087538/ (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt0101862/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A36B6C96A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt0343660/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A36B6C9C70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt0448157/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A36B6C91C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt0327056/ (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt0790636/ (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt0325980/ (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt1772341/ (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt0257044/ (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt0120601/ (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt0118883/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A36A7871F0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt10954984/ (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt5462602/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002A36B434070>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt1289403/ (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt0056592/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000018679C362B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt3183660/ (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt11422728/ (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt0055630/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001867A38FB20>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt5074352/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001867A882D60>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt8613070/ (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))": 1, "('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt0006864/ (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt0060675/ (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt0055852/ (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt0070034/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000018679F55340>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt0388795/ (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt4028464/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001867A55CE80>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt0056687/ (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt0082010/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000018678F91F40>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt2713180/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001867A5BDD60>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt7557108/ (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))": 1, "HTTPSConnectionPool(host='www.imdb.com', port=443): Max retries exceeded with url: /title/tt13321244/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001867A55C160>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='imdb.com', port=443): Max retries exceeded with url: /title/tt10651230/ (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)')))": 1, "('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))": 1}, "https://www.rottentomatoes.com/m/": {"count": 2, "name 'rotten' is not defined": 2}, "https://www.rottentomatoes.com/search?search=operation%20mekong": {"count": 2, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=operation%20mekong (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002CAAB4A4B80>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=operation%20mekong (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002661D206AF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1}, "https://www.rottentomatoes.com/search?search=okja": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=okja (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002CAAB4AC460>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1}, "https://www.rottentomatoes.com/search?search=black%20hawk%20down": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=black%20hawk%20down (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002661CD9C820>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1}, "https://www.rottentomatoes.com/m/boondock_saints": {"count": 1, "Can't fetch current ip, even after retrying... Check your internet connection.": 1}, "https://www.rottentomatoes.com/search?search='71": {"count": 1, "(\"Connection broken: ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)\", ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))": 1}, "https://www.rottentomatoes.com/search?search=leviathan": {"count": 1, "('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))": 1}, "https://www.rottentomatoes.com/search?search=freetown": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=freetown (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002661D206BB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1}, "https://www.rottentomatoes.com/search?search=the%20goonies": {"count": 1, "('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))": 1}, "https://www.rottentomatoes.com/search?search=the%20bourne%20ultimatum": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=the%20bourne%20ultimatum (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000221679CC1C0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1}, "https://www.rottentomatoes.com/search?search=north%20by%20northwest": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=north%20by%20northwest (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000221679D37C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1}, "https://www.rottentomatoes.com/m/american_made_2017": {"count": 1, "(\"Connection broken: ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)\", ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))": 1}, "https://www.rottentomatoes.com/search?search=everything%20everywhere%20all%20at%20once": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=everything%20everywhere%20all%20at%20once (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022166EA9B50>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1}, "https://www.rottentomatoes.com/search?search=avengers:%20infinity%20war": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=avengers:%20infinity%20war (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022166E8D4F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1}, "https://www.rottentomatoes.com/search?search=kingsman:%20the%20secret%20service": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=kingsman:%20the%20secret%20service (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022166E8D400>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1}, "https://www.rottentomatoes.com/m/tangled": {"count": 1, "('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))": 1}, "https://www.rottentomatoes.com/search?search=ponyo": {"count": 1, "Can't fetch current ip, even after retrying... Check your internet connection.": 1}, "https://www.rottentomatoes.com/search?search=beetlejuice": {"count": 1, "('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))": 1}, "https://www.rottentomatoes.com/search?search=trading%20places": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=trading%20places (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022166F355E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1}, "https://www.rottentomatoes.com/search?search=spies%20like%20us": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=spies%20like%20us (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022166F354C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1}, "https://www.rottentomatoes.com/search?search=overboard": {"count": 1, "(\"Connection broken: ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)\", ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))": 1}, "https://www.rottentomatoes.com/search?search=scott%20pilgrim%20vs.%20the%20world": {"count": 1, "('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))": 1}, "https://www.rottentomatoes.com/search?search=thelma%20&%20louise": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=thelma%20&%20louise (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002216767E760>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1}, "https://www.rottentomatoes.com/m/the_girl_with_the_dragon_tattoo": {"count": 1, "Can't fetch current ip, even after retrying... Check your internet connection.": 1}, "https://www.rottentomatoes.com/m/oppenheimer_2023": {"count": 1, "('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))": 1}, "https://www.rottentomatoes.com/search?search=moonlight": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=moonlight (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002216779E190>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1}, "https://www.rottentomatoes.com/m/room_2015": {"count": 1, "('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))": 1}, "https://www.rottentomatoes.com/search?search=lawrence%20of%20arabia": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=lawrence%20of%20arabia (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000221679BCC10>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1}, "https://www.rottentomatoes.com/search?search=incendies": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=incendies (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000221679B8A00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1}, "https://www.rottentomatoes.com/search?search=remember%20the%20titans": {"count": 1, "('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))": 1}, "https://www.rottentomatoes.com/search?search=the%20power%20of%20one": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=the%20power%20of%20one (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000221679BDC10>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1}, "https://www.rottentomatoes.com/m/capernaum": {"count": 1, "('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))": 1}, "https://www.rottentomatoes.com/search?search=lincoln": {"count": 1, "(\"Connection broken: ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)\", ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))": 1}, "https://www.rottentomatoes.com/search?search=philadelphia": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=philadelphia (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022167615B20>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1}, "https://www.rottentomatoes.com/search?search=creed": {"count": 1, "(\"Connection broken: ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)\", ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))": 1}, "https://www.rottentomatoes.com/m/snowden": {"count": 1, "('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))": 1}, "https://www.rottentomatoes.com/search?search=carol": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=carol (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022167941040>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1}, "https://www.rottentomatoes.com/search?search=manchester%20by%20the%20sea": {"count": 1, "('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))": 1}, "https://www.rottentomatoes.com/search?search=the%20neverending%20story": {"count": 1, "('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))": 1}, "https://www.rottentomatoes.com/m/the_hobbit_the_battle_of_the_five_armies": {"count": 1, "('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))": 1}, "https://www.rottentomatoes.com/search?search=hostel": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=hostel (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000221679ACF10>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1}, "https://www.rottentomatoes.com/m/exorcist": {"count": 1, "('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))": 1}, "https://www.rottentomatoes.com/m/the_greatest_showman_2017": {"count": 1, "(\"Connection broken: ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)\", ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))": 1}, "https://www.rottentomatoes.com/search?search=before%20sunrise": {"count": 1, "('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))": 1}, "https://www.rottentomatoes.com/search?search=the%20notebook": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=the%20notebook (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022167E23BE0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1}, "https://www.rottentomatoes.com/search?search=titanic": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=titanic (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002216809BD30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1}, "https://www.rottentomatoes.com/m/star_wars_episode_v_the_empire_strikes_back": {"count": 1, "('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))": 1}, "https://www.rottentomatoes.com/search?search=the%20fifth%20element": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=the%20fifth%20element (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022167185580>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1}, "https://www.rottentomatoes.com/search?search=dune:%20part%20two": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=dune:%20part%20two (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022167537C70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1}, "https://www.rottentomatoes.com/search?search=edge%20of%20tomorrow": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=edge%20of%20tomorrow (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002216733BFA0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1}, "https://www.rottentomatoes.com/m/district_9": {"count": 1, "('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))": 1}, "https://www.rottentomatoes.com/search?search=blade%20runner": {"count": 1, "(\"Connection broken: ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)\", ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))": 1}, "https://www.rottentomatoes.com/search?search=rise%20of%20the%20planet%20of%20the%20apes": {"count": 1, "('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))": 1}, "https://www.rottentomatoes.com/search?search=total%20recall": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=total%20recall (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022167FC7520>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1}, "https://www.rottentomatoes.com/m/avatar_the_way_of_water": {"count": 1, "('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))": 1}, "https://www.rottentomatoes.com/search?search=man%20on%20fire": {"count": 1, "('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))": 1}, "https://www.rottentomatoes.com/search?search=munich": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=munich (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000221675839D0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1}, "https://www.rottentomatoes.com/search?search=transsiberian": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=transsiberian (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022167A18400>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1}, "https://www.rottentomatoes.com/m/american_psycho": {"count": 1, "(\"Connection broken: ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)\", ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))": 1}, "https://www.rottentomatoes.com/search?search=lucky%20number%20slevin": {"count": 1, "('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))": 1}, "https://www.rottentomatoes.com/m/bridge_on_the_river_kwai": {"count": 1, "('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))": 1}, "https://www.rottentomatoes.com/search?search=chinatown": {"count": 1, "(\"Connection broken: ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)\", ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))": 1}, "https://www.rottentomatoes.com/search?search=the%20thin%20man": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=the%20thin%20man (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002216778DB80>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1}, "https://www.rottentomatoes.com/search?search=past%20lives": {"count": 1, "(\"Connection broken: ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)\", ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))": 1}, "https://www.rottentomatoes.com/search?search=the%20fabelmans": {"count": 1, "(\"Connection broken: ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)\", ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))": 1}, "https://www.rottentomatoes.com/m/the_hamster_factor_and_other_tales_of_12_monkeys_1997": {"count": 1, "Can't fetch current ip, even after retrying... Check your internet connection.": 1}, "https://www.rottentomatoes.com/search?search=what%20ever%20happened%20to%20baby%20jane?": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=what%20ever%20happened%20to%20baby%20jane? (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000221677A5F40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1}, "https://www.rottentomatoes.com/search?search=infernal%20affairs": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=infernal%20affairs (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000221677A5BE0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1}, "https://www.rottentomatoes.com/m/the_trial_of_the_chicago_7": {"count": 1, "('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))": 1}, "https://www.rottentomatoes.com/search?search=breakfast%20at%20tiffany's": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=breakfast%20at%20tiffany's (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000221673A0460>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1}, "https://www.rottentomatoes.com/search?search=mad%20max%202:%20the%20road%20warrior": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=mad%20max%202:%20the%20road%20warrior (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022167396220>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1}, "https://www.rottentomatoes.com/search?search=midnight%20run": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=midnight%20run (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000221673962E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1}, "https://www.rottentomatoes.com/search?search=nowhere%20special": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=nowhere%20special (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002216733B190>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1}, "https://www.rottentomatoes.com/m/1037756-jfk": {"count": 1, "('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))": 1}, "https://www.rottentomatoes.com/search?search=days%20of%20wine%20and%20roses": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=days%20of%20wine%20and%20roses (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022167FE35E0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1}, "https://www.rottentomatoes.com/search?search=the%20royal%20tenenbaums": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=the%20royal%20tenenbaums (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022167F03160>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1}, "https://www.rottentomatoes.com/search?search=blackberry": {"count": 1, "('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))": 1}, "https://www.rottentomatoes.com/search?search=speed": {"count": 1, "(\"Connection broken: ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)\", ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))": 1}, "https://www.rottentomatoes.com/search?search=the%20breaking%20point": {"count": 1, "('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))": 1}, "https://www.rottentomatoes.com/search?search=frida": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=frida (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022167069F10>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1}, "https://www.rottentomatoes.com/search?search=song%20for%20a%20raggy%20boy": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=song%20for%20a%20raggy%20boy (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022167069760>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1}, "https://www.rottentomatoes.com/search?search=forgotten%20love": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=forgotten%20love (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000221670694F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1}, "https://www.rottentomatoes.com/m/1037024-commitments": {"count": 1, "(\"Connection broken: ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)\", ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))": 1}, "https://www.rottentomatoes.com/search?search=one%20life": {"count": 1, "Can't fetch current ip, even after retrying... Check your internet connection.": 1}, "https://www.rottentomatoes.com/search?search=funny%20games": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=funny%20games (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000221677CE7C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1}, "https://www.rottentomatoes.com/search?search=babel": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=babel (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022166CC2850>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1}, "https://www.rottentomatoes.com/m/lost_highway": {"count": 1, "Can't fetch current ip, even after retrying... Check your internet connection.": 1}, "https://www.rottentomatoes.com/search?search=dead%20alive": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=dead%20alive (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002216727CE80>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1}, "https://www.rottentomatoes.com/search?search=cloud%20atlas": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=cloud%20atlas (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002216727CE50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1}, "https://www.rottentomatoes.com/m/citizen_kane": {"count": 1, "name 'dev' is not defined": 1}, "https://www.rottentomatoes.com/m/jules_and_jim": {"count": 1, "(\"Connection broken: ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)\", ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))": 1}, "https://www.rottentomatoes.com/search?search=rocks": {"count": 1, "('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))": 1}, "https://www.rottentomatoes.com/m/45_years": {"count": 1, "(\"Connection broken: ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)\", ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))": 1}, "https://www.rottentomatoes.com/search?search=hannah%20and%20her%20sisters": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=hannah%20and%20her%20sisters (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022E8852D280>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1}, "https://www.rottentomatoes.com/search?search=high%20and%20low": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=high%20and%20low (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022E8852DF70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1}, "https://www.rottentomatoes.com/search?search=i%20called%20him%20morgan": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=i%20called%20him%20morgan (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022E8850B040>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1}, "https://www.rottentomatoes.com/search?search=it's%20such%20a%20beautiful%20day": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=it's%20such%20a%20beautiful%20day (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022E8850B190>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1}, "https://www.rottentomatoes.com/search?search=deep%20red": {"count": 1, "(\"Connection broken: ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)\", ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))": 1}, "https://www.rottentomatoes.com/search?search=great%20freedom": {"count": 1, "('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))": 1}, "https://www.rottentomatoes.com/search?search=high%20noon": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=high%20noon (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022E8785BC40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1}, "https://www.rottentomatoes.com/search?search=house%20of%20flying%20daggers": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=house%20of%20flying%20daggers (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022E8785BD00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1}, "https://www.rottentomatoes.com/search?search=letters%20from%20iwo%20jima": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=letters%20from%20iwo%20jima (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022E8777A1F0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1}, "https://www.rottentomatoes.com/search?search=piccadilly%20[re-release]": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=piccadilly%20%5Bre-release%5D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022E879E1700>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1}, "https://www.rottentomatoes.com/search?search=quai%20des%20orf\u00e8vres%20[re-release]": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=quai%20des%20orf%C3%A8vres%20%5Bre-release%5D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022E879E1700>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1}, "https://www.rottentomatoes.com/search?search=still%20walking": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=still%20walking (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022E87C01C10>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1}, "https://www.rottentomatoes.com/search?search=the%20artist": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=the%20artist (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022E87BFD460>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1}, "https://www.rottentomatoes.com/search?search=the%20best%20of%20youth": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=the%20best%20of%20youth (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022E87BFD4C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1}, "https://www.rottentomatoes.com/search?search=the%20farewell": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=the%20farewell (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022E87BFD2E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1}, "https://www.rottentomatoes.com/search?search=two-lane%20blacktop": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=two-lane%20blacktop (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022E882DC670>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1}, "https://www.rottentomatoes.com/search?search=uncertain": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=uncertain (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022E882E2A90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1}, "https://www.rottentomatoes.com/search?search=the%20death%20of%20stalin": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=the%20death%20of%20stalin (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022E87802B50>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1}, "https://www.rottentomatoes.com/m/4_little_girls": {"count": 1, "('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))": 1}, "https://www.rottentomatoes.com/search?search=45365": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=45365 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022E8815FB80>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1}, "https://www.rottentomatoes.com/search?search=a%20film%20unfinished": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=a%20film%20unfinished (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022E8816F430>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1}, "https://www.rottentomatoes.com/search?search=a%20woman%20under%20the%20influence": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /search?search=a%20woman%20under%20the%20influence (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022E8816F8E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1}, "https://www.rottentomatoes.com/m/anomalisa": {"count": 1, "HTTPSConnectionPool(host='www.rottentomatoes.com', port=443): Max retries exceeded with url: /m/anomalisa (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022E8875C730>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1}, "https://finance.yahoo.com/quote/": {"count": 136, "'NoneType' object is not callable": 4, "list index out of range": 3, "[Errno 13] Permission denied: 'C:\\\\Users\\\\Burt\\\\Documents\\\\Git\\\\podcast\\\\stocks_meta.xlsx'": 1, "argument of type 'NoneType' is not iterable": 59, "(\"Connection broken: ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)\", ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))": 5, "('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))": 1, "('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))": 10, "HTTPSConnectionPool(host='finance.yahoo.com', port=443): Max retries exceeded with url: /quote/MUFG (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000011CA57102E0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='finance.yahoo.com', port=443): Max retries exceeded with url: /quote/C (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000011CA570A430>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))": 22, "HTTPSConnectionPool(host='finance.yahoo.com', port=443): Max retries exceeded with url: /quote/GD (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000011CA6E45340>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='finance.yahoo.com', port=443): Max retries exceeded with url: /quote/SMFG (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000011CA6E45280>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='finance.yahoo.com', port=443): Max retries exceeded with url: /quote/MBG.DE/analysis (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000011CA68C4070>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "Can't fetch current ip, even after retrying... Check your internet connection.": 5, "HTTPSConnectionPool(host='finance.yahoo.com', port=443): Max retries exceeded with url: /quote/SPOT (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002051FB63730>: Failed to establish a new connection: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions'))": 1, "HTTPSConnectionPool(host='finance.yahoo.com', port=443): Max retries exceeded with url: /quote/SPG (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002051EA7D130>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='finance.yahoo.com', port=443): Max retries exceeded with url: /quote/2914.T (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002051EF017C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='finance.yahoo.com', port=443): Max retries exceeded with url: /quote/GIVN.SW (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020520C300D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='finance.yahoo.com', port=443): Max retries exceeded with url: /quote/BN.PA (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020520C301F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='finance.yahoo.com', port=443): Max retries exceeded with url: /quote/ADANIENT.NS/analysis (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002051E9F7BE0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='finance.yahoo.com', port=443): Max retries exceeded with url: /quote/MSFT/history (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C1A4BFCA90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='finance.yahoo.com', port=443): Max retries exceeded with url: /quote/BHARTIARTL.NS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000015AAE0CDFD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='finance.yahoo.com', port=443): Max retries exceeded with url: /quote/EFX (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000015AAEB3A2B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='finance.yahoo.com', port=443): Max retries exceeded with url: /quote/SIRI (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000015AAE3A1DF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='finance.yahoo.com', port=443): Max retries exceeded with url: /quote/BZLA.F (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000015AAE0321F0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='finance.yahoo.com', port=443): Max retries exceeded with url: /quote/ARGX (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000015AAE04E820>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='finance.yahoo.com', port=443): Max retries exceeded with url: /quote/VBL.NS (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000015AAE9A3580>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='finance.yahoo.com', port=443): Max retries exceeded with url: /quote/ROL (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000015AAFAFE400>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='finance.yahoo.com', port=443): Max retries exceeded with url: /quote/000725.SZ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000015AAD9D1070>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='finance.yahoo.com', port=443): Max retries exceeded with url: /quote/PBA (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000015AAF70D9D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='finance.yahoo.com', port=443): Max retries exceeded with url: /quote/STMN.SW (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000015AAF70DAC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='finance.yahoo.com', port=443): Max retries exceeded with url: /quote/DKNG (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000015AAE4C3130>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='finance.yahoo.com', port=443): Max retries exceeded with url: /quote/WSM (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000015AAD9D6610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))": 1, "HTTPSConnectionPool(host='finance.yahoo.com', port=443): Max retries exceeded with url: /quote/ANTM (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A27A6FD550>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1, "HTTPSConnectionPool(host='finance.yahoo.com', port=443): Max retries exceeded with url: /quote/F34.SI (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A27A767670>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))": 1}}